{{- if and .Values.cloudflare.apiToken (not .Values.cloudflare.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflare.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: homelab-cert-manager
type: Opaque
stringData:
  {{ .Values.cloudflare.secretKey }}: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
