{{- $ctx := dict "root" $ "component" "storage-broker" }}
{{- $fullname := include "neon.fullname" $ctx }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "neon.labels" $ctx | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "neon.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "neon.selectorLabels" $ctx | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      enableServiceLinks: false
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: storage-broker
          image: {{ include "neon.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            - /usr/local/bin/storage_broker
          args:
            - --listen-addr=0.0.0.0:{{ $.Values.storageBroker.port }}
          ports:
            - name: broker
              containerPort: {{ $.Values.storageBroker.port }}
              protocol: TCP
          resources:
            {{- toYaml $.Values.storageBroker.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "neon.labels" $ctx | nindent 4 }}
spec:
  selector:
    {{- include "neon.selectorLabels" $ctx | nindent 4 }}
  ports:
    - name: broker
      port: {{ $.Values.storageBroker.port }}
      targetPort: broker
